[pluginManagement]
repositories = [
    { url = "https://plugins.gradle.org/m2/" },
    { url = "https://maven.google.com" },
    { url = "https://repo.maven.apache.org/maven2" }
]

[versions]
kotlin = "2.0.21"
hilt = "2.44"
ksp = "1.0.0"
