include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - import_lint

linter:
  rules:
    always_put_control_body_on_new_line: true
    always_put_required_named_parameters_first: true
    require_trailing_commas: true
    avoid_print: true
    always_use_package_imports: true
    always_declare_return_types: true
    annotate_overrides: true
    cancel_subscriptions: true
    prefer_double_quotes: true
    prefer_void_to_null: true
    sort_constructors_first: true
    unawaited_futures: true
    unnecessary_breaks: true