package com.example.musicapp.util

object FirebaseKey {
    const val SONGS = "songs"
    const val SONG_THUMBNAILS = "song_thumbnails"
    const val ARTISTS = "artists"
    const val ALBUMS = "albums"
    const val PLAYLISTS = "playlists"
    const val USERS = "users"
    const val USER_SONGS = "user_songs"
    const val USER_PLAYLISTS = "user_playlists"
    const val USER_ARTISTS = "user_artists"
    const val USER_ALBUMS = "user_albums"
    const val USER_LIKED_SONGS = "user_liked_songs"
    const val USER_LIKED_ALBUMS = "user_liked_albums"
    const val USER_LIKED_ARTISTS = "user_liked_artists"
    const val USER_LIKED_PLAYLISTS = "user_liked_playlists"
    const val USER_FOLLOWING = "user_following"
    const val USER_FOLLOWERS = "user_followers"
    const val USER_FOLLOWING_ARTISTS = "user_following_artists"
    const val USER_FOLLOWING_PLAYLISTS = "user_following_playlists"
    const val USER_FOLLOWING_ALBUMS = "user_following_albums"
    const val USER_FOLLOWING_SONGS = "user_following_songs"
    const val USER_FOLLOWING_USERS = "user_following_users"
    const val USER_FOLLOWING_ARTIST_SONGS = "user_following_artist_songs"
    const val USER_FOLLOWING_PLAYLIST_SONGS = "user_following_playlist_songs"
    const val USER_FOLLOWING_USER_SONGS = "user_following_user_songs"
    const val USER_FOLLOWING_ARTIST_ALBUMS = "user_following_artist_albums"
    const val USER_FOLLOWING_ARTIST_PLAYLISTS = "user_following_artist_playlists"
    const val USER_FOLLOWING_ARTIST_ARTISTS = "user_following_artist_artists"
    const val USER_FOLLOWING_ALBUM_ARTISTS = "user_following_album_artists"
    const val USER_FOLLOWING_ALBUM_PLAYLISTS = "user_following_album_playlists"
    const val USER_FOLLOWING_ALBUM_SONGS = "user_following_album_songs"
    const val USER_FOLLOWING_PLAYLIST_ARTISTS = "user_following_playlist_artists"
}